# Generated by Django 6.0.8 on 2026-08-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-popularity_score', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='car',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='car',
            name='popularity_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='car',
            name='recommendation_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='car',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for search', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Searchable tags'),
        ),
        migrations.AddField(
            model_name='car',
            name='times_rented',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='popularity_score',
            field=models.FloatField(default=0.0, help_text='Auto-calculated popularity score'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand', 'model'], name='vehicles_ca_brand_247376_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price_per_day'], name='vehicles_ca_price_p_d1d00b_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status', 'category'], name='vehicles_ca_status_ab2226_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='vehicles_ca_year_30c391_idx'),
        ),
    ]
