# Generated by Django 6.0.6 on 2026-08-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='view_type',
            field=models.CharField(blank=True, choices=[('FRONT', 'Front View'), ('SIDE', 'Side Profile'), ('REAR', 'Rear View'), ('INTERIOR', 'Interior & Seating'), ('DASHBOARD', 'Dashboard & Controls'), ('ANGLE', '3/4 Perspective View'), ('OTHER', 'Detail / Feature')], default='OTHER', max_length=20),
        ),
    ]
