# Generated by Django 6.0.6 on 2026-08-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_carimage_view_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='main_image_url',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='car',
            name='main_image_path',
            field=models.CharField(blank=True, help_text='Supabase Storage path, e.g. cars/15/main.jpg', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carimage',
            name='image_path',
            field=models.CharField(blank=True, help_text='Supabase Storage path, e.g. gallery/15/1.jpg', max_length=255, null=True),
        ),
    ]
