# Generated by Django 6.0.8 on 2026-08-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_category_options_car_average_rating_and_more'),
        ('vehicles', '0002_carimage_view_type'),
    ]

    operations = [
    ]
