# Generated by Django 6.0.6 on 2026-08-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_path',
            field=models.CharField(blank=True, help_text='Supabase Storage path, e.g. profiles/42/profile.jpg', max_length=255, null=True),
        ),
    ]
