# Generated by Django 6.0.6 on 2026-08-20 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_bookings', to='vehicles.location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_bookings', to='vehicles.location'),
        ),
        migrations.AddField(
            model_name='bookingaddon',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.coupon'),
        ),
    ]
