# Generated by Django 6.0.6 on 2026-08-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 20 for 20%) or Fixed rupee amount', max_digits=10),
        ),
    ]
