# Generated by Django 6.0.8 on 2026-08-27 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_alter_category_options_car_average_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPopularityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_last_7_days', models.PositiveIntegerField(default=0)),
                ('views_last_30_days', models.PositiveIntegerField(default=0)),
                ('bookings_last_30_days', models.PositiveIntegerField(default=0)),
                ('booking_conversion_rate', models.FloatField(default=0.0)),
                ('average_daily_views', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_metrics', to='vehicles.car')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(max_length=50)),
                ('position', models.PositiveIntegerField()),
                ('clicked', models.BooleanField(default=False)),
                ('booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['car', 'recommendation_type'], name='analytics_r_car_id_977ccf_idx'), models.Index(fields=['user', 'created_at'], name='analytics_r_user_id_6728be_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='analytics_s_user_id_2cb926_idx'), models.Index(fields=['query'], name='analytics_s_query_86cb43_idx')],
            },
        ),
    ]
