# Generated by Django 6.0.6 on 2026-08-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('BOOKING', 'Booking Update'), ('PAYMENT', 'Payment Confirmation'), ('REMINDER', 'Trip Reminder'), ('ALERT', 'Important Alert'), ('PROMO', 'Special Promotion')], default='ALERT', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('link_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
